# Cấu hình SMTP gửi mail OTP cho Đồ án WebExamDe05
# Bạn có thể điền thông tin Email Gmail và App Password thực tế của bạn bên dưới
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.user=your_email@gmail.com
mail.password=your_app_password
